import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { ServiceDiscoveryService } from './serviceDiscoveryService.js';

export class LoadBalancerService {
    /**
     * Generates Nginx upstream configuration block for a specific app.
     * @param {string} appName
     * @param {string} strategy 'round-robin', 'least_conn', or 'ip_hash'
     */
    static generateUpstreamConfig(appName, strategy = 'round-robin') {
        const instances = ServiceDiscoveryService.discoverService(appName);
        const healthyInstances = instances.filter(i => i.health_status === 'healthy' || i.health_status === 'unknown');
        
        if (healthyInstances.length === 0) {
            return `# No healthy instances found for ${appName}\n`;
        }

        let config = `upstream backend_${appName} {\n`;
        
        if (strategy === 'least_conn') {
            config += `    least_conn;\n`;
        } else if (strategy === 'ip_hash') {
            config += `    ip_hash;\n`;
        }

        healthyInstances.forEach(instance => {
            config += `    server ${instance.host}:${instance.port};\n`;
        });

        config += `}\n`;
        return config;
    }

    /**
     * Generates a complete Nginx configuration for the cluster load balancer.
     */
    static generateFullConfig() {
        const services = ServiceDiscoveryService.getAllServices();
        
        // Group services by appName
        const apps = [...new Set(services.map(s => s.app_name))];
        
        let fullConfig = `# PixelPanel Cluster Load Balancer Configuration\n`;
        fullConfig += `# Auto-generated by LoadBalancerService\n\n`;

        apps.forEach(app => {
            fullConfig += this.generateUpstreamConfig(app, 'round-robin');
            fullConfig += '\n';
        });

        return fullConfig;
    }

    /**
     * Writes the configuration to disk and reloads Nginx.
     */
    static async applyConfig() {
        return new Promise((resolve, reject) => {
            const configStr = this.generateFullConfig();
            const configPath = '/etc/nginx/conf.d/pixelpanel-cluster.conf';

            try {
                // In a real environment with root/sudo access:
                // fs.writeFileSync(configPath, configStr);
                
                // For development/mock:
                const devPath = path.join(process.cwd(), 'pixelpanel-cluster.conf.tmp');
                fs.writeFileSync(devPath, configStr);
                
                // Reload nginx
                // exec('sudo systemctl reload nginx', (err, stdout, stderr) => { ... });
                resolve({ success: true, message: 'Load balancer config applied successfully.' });
            } catch (error) {
                reject(error);
            }
        });
    }
}
