import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import util from 'util';

const execPromise = util.promisify(exec);

// Path where Nginx looks for virtual host configs
const NGINX_CONF_DIR = process.env.NGINX_CONF_DIR || '/etc/nginx/sites-available';
const NGINX_ENABLED_DIR = process.env.NGINX_ENABLED_DIR || '/etc/nginx/sites-enabled';

export class NginxService {
    /**
     * Generate Reverse Proxy Configuration for an App
     * Supports scale-to-zero and automated SSL via Let's Encrypt
     */
    static async generateConfig(appName, domain, internalPort, app, enableScaleToZero = false, enableSSL = false) {
        const username = `pxl_app_${app.id}`;
        const uploadPath = `/var/www/pixelpanel/${username}/uploads`;
        
        // Ensure the global upload path exists
        try {
            await execPromise(`sudo mkdir -p ${uploadPath}`);
            await execPromise(`sudo chown -R ${username}:${username} ${uploadPath}`);
            await execPromise(`sudo chmod -R 700 ${uploadPath}`);
        } catch (e) {}

        let configTemplate = `
# Nginx Configuration for ${appName}
# Auto-generated by PixelPanel Blue-Green Engine

server {
    listen 80;
    server_name ${domain};
    
    # Isolated Sandbox Logging
    access_log /var/log/pixelpanel/${username}/access.log;
    error_log /var/log/pixelpanel/${username}/error.log;

    # Public Uploads Directory mapped to the Sandbox
    location /uploads/ {
        alias ${uploadPath}/;
        # allow read-only for nginx (www-data), handled by acl
        try_files $uri $uri/ =404;
    }

    location / {
        proxy_pass http://127.0.0.1:${internalPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Scale to Zero Wakeup Hook (Redirects 502 to PixelPanel Wake Service)
        ${enableScaleToZero ? `
        error_page 502 = @wakeup;
        ` : ''}
    }
    
    ${enableScaleToZero ? `
    location @wakeup {
        proxy_pass http://127.0.0.1:3000/api/internal/wakeup/${appName};
        proxy_set_header X-Original-URI $request_uri;
    }
    ` : ''}
}
`;
        const confPath = path.join(NGINX_CONF_DIR, `${appName}.conf`);
        const symlinkPath = path.join(NGINX_ENABLED_DIR, `${appName}.conf`);

        try {
            // Write config
            fs.writeFileSync(confPath, configTemplate);
            
            // Create symlink if it doesn't exist
            if (!fs.existsSync(symlinkPath)) {
                fs.symlinkSync(confPath, symlinkPath);
            }

            // Reload Nginx gracefully
            await execPromise('nginx -s reload');

            // Provision SSL if requested
            if (enableSSL) {
                console.log(`[NginxService] Provisioning SSL for ${domain}...`);
                try {
                    await execPromise(`certbot --nginx -d ${domain} --non-interactive --agree-tos -m admin@pixelpanel.local`);
                } catch (sslErr) {
                    console.error('[NginxService] SSL Provisioning failed. Is certbot installed and domain pointing here?', sslErr.message);
                    // We don't throw, as the app is still accessible via HTTP
                }
            }
            
            return { success: true };
        } catch (error) {
            console.error('[NginxService] Error generating config:', error);
            throw new Error(`Failed to configure Nginx: ${error.message}`);
        }
    }

    /**
     * Remove Nginx Config
     */
    static async removeConfig(appName) {
        const confPath = path.join(NGINX_CONF_DIR, `${appName}.conf`);
        const symlinkPath = path.join(NGINX_ENABLED_DIR, `${appName}.conf`);

        try {
            if (fs.existsSync(symlinkPath)) fs.unlinkSync(symlinkPath);
            if (fs.existsSync(confPath)) fs.unlinkSync(confPath);
            
            await execPromise('nginx -s reload');
            return { success: true };
        } catch (error) {
            console.error('[NginxService] Error removing config:', error);
            throw new Error(`Failed to remove Nginx config: ${error.message}`);
        }
    }
}
